draimcraft:
  # если вы хотите отключить плагин, установите значение false
  enabled: true
  config-reloaded: "&7Конфигурация перезапущена!"
  # используйте %command% для получения синтаксиса команды
  incorrect-syntax: "&7Пропишите команду - &6%command%"
  # сообщение, которое отправляется игроку после попытки создать запрещенный предмет
  # используйте %item%, чтобы получить название предметов
  message: '&7Вы не можете скрафтить %item%'
  # установите значение false, если вы не хотите заблокировать создание ВСЕХ предметов в игре
  block-all-items: true
  # список материалов, которые вы хотели бы заблокировать от создания, если для параметра block-all-items установлено значение false
  # примечание: элементы, перечисленные в default-block-list, все равно будут заблокированы, даже если вы используете группы
  # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
  default-block-list:
    - 'TORCH'
  # запретить создание определенных рецептов для групп, работает в дополнение с default-block-list
  # просто используйте 'limitcrafting.groups.<название-группы>' в разрешениях, чтобы блокировать рецепты для определенных групп
  enable-groups: false
  groups:
    default:
      - 'OAK_PLANKS'
    dev:
      - 'BUCKET'